# -*- coding: utf-8 -*-
"""MarvinGPT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0Q_ZvfC3B4DaCJ1CLNw0uInxG789mm-
"""

import tensorflow as tf

name = "MarvinGPT"
version = "v0.1.0"
creator = "Ebuka"

print(name, " ", version, " Creator: ", creator)
print(tf.version)